# FAZENDO O DOWNLOAD DO NODE NA VERSAO 16.15.1 DIRETAMENTO DO DOCKERHUB
FROM node:16.15.1

# DEFININDO UMA VARIÁVEL DE AMBIENTE PORT COM O VALOR 3000 
ENV PORT=3000

# EXPONDO A PORTA 3000 DO CONTAINER
EXPOSE 3000

# DEFININDO UM DIRETÓRIO DE TRABALHO CHAMADO /app
WORKDIR /app

# COPIANDO O package.json PARA O DIRETÓRIO /app DEFINIDO ANTERIORMENTE
COPY 'package.json' .

# EXECUTANDO O yarn PARA INSTALAR AS DEPENDENCIAS E CRIAR O node_modules
RUN yarn

# COPIANDO O RESTANTE DA APLICAÇÃO PARA O DIRETÓRIO /app
COPY . .

# EXECUTANDO O yarn dev QUE IRÁ COLOCAR A APLICAÇÃO NO AR DENTRO DO CONTAINER
CMD ["yarn", "dev"]